// <auto-generated />
using System;
using Ensemble.Maestro.Dotnet.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ensemble.Maestro.Dotnet.Migrations
{
    [DbContext(typeof(MaestroDbContext))]
    [Migration("20250829115414_RemoveFunctionSpecificationForeignKeys")]
    partial class RemoveFunctionSpecificationForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AgentSpecialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("ContextData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ExecutionCost")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("ExecutionLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionCalls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrchestrationPattern")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OutputResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerformanceMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PluginsUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<Guid?>("StageExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("ParentExecutionId");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StageExecutionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "AgentType", "Status");

                    b.ToTable("AgentExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ContentLength")
                        .HasColumnType("int");

                    b.Property<string>("ContextData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionCallData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionCallResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRetry")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationContext")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("int");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("int");

                    b.Property<bool>("TriggeredFunctionCall")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MessageType");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("Role");

                    b.HasIndex("SequenceNumber");

                    b.HasIndex("ThreadId");

                    b.HasIndex("AgentExecutionId", "SequenceNumber");

                    b.ToTable("AgentMessages");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.CodeUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedController")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("CodeSize")
                        .HasColumnType("bigint");

                    b.Property<string>("CodeStats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("int");

                    b.Property<int>("ComplexFunctionCount")
                        .HasColumnType("int");

                    b.Property<int>("ComplexityRating")
                        .HasColumnType("int");

                    b.Property<string>("Constructors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ControllerAssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ControllerExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CrossReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dependencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DesignerOutputId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Fields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FunctionCount")
                        .HasColumnType("int");

                    b.Property<string>("GeneratedCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImplementationCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ImplementationStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inheritance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Integrations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MethodAgentCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Patterns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceConsiderations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProcessingStage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityConsiderations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SimpleFunctionCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestingStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedController");

                    b.HasIndex("ComplexityRating");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CrossReferenceId");

                    b.HasIndex("DesignerOutputId");

                    b.HasIndex("Language");

                    b.HasIndex("ModuleId");

                    b.HasIndex("Name");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("UnitType");

                    b.HasIndex("Language", "UnitType");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("CodeUnits");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.CrossReferenceEntity", b =>
                {
                    b.Property<Guid>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ElasticsearchId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastIntegrityCheck")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neo4jId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("SqlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("PrimaryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.HasIndex("LastIntegrityCheck");

                    b.HasIndex("Status");

                    b.HasIndex("EntityType", "Status");

                    b.ToTable("CrossReferences");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.DesignerOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApiSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArchitectureOverview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComplexityRating")
                        .HasColumnType("int");

                    b.Property<string>("ComponentSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CrossReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DatabaseSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeploymentSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeploymentTarget")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExecutionCost")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int>("FunctionSpecsCount")
                        .HasColumnType("int");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<string>("IntegrationSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkdownOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("PerformanceSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProcessingStage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QualityScore")
                        .HasColumnType("int");

                    b.Property<string>("SecuritySpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SpecsExtractedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StructuredData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestingSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UiSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CrossReferenceId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "AgentType", "Status");

                    b.ToTable("DesignerOutputs");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.FunctionSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessLogic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeUnit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CodeUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletenessPercentage")
                        .HasColumnType("int");

                    b.Property<int>("ComplexityRating")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedByAgent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CrossReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dependencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DesignerOutputId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorHandling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ImplementedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InputParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Namespace")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PerformanceRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<string>("ReturnType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityConsiderations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestCases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("CodeUnit");

                    b.HasIndex("CodeUnitId");

                    b.HasIndex("ComplexityRating");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CrossReferenceId");

                    b.HasIndex("DesignerOutputId");

                    b.HasIndex("FunctionName");

                    b.HasIndex("Language");

                    b.HasIndex("ModuleId");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("Priority");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("Language", "ComplexityRating");

                    b.HasIndex("ProjectId", "CodeUnit", "Status");

                    b.ToTable("FunctionSpecifications");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComplexityScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Dependencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleOrder")
                        .HasColumnType("int");

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalStack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ModuleOrder");

                    b.HasIndex("ModuleType");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.OrchestrationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgentCount")
                        .HasColumnType("int");

                    b.Property<string>("CancellationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("ContextData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DidTimeout")
                        .HasColumnType("bit");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionFlow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FunctionCallCount")
                        .HasColumnType("int");

                    b.Property<string>("InitialInput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputTransformations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrchestrationPattern")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OutputTransformations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentOrchestrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParticipatingAgents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<string>("RuntimeConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SuccessRate")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.Property<string>("Warnings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasCancelled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationPattern");

                    b.HasIndex("ParentOrchestrationId");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("OrchestrationResults");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("AgentPoolSize")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedFunctions")
                        .HasColumnType("int");

                    b.Property<string>("DeploymentTarget")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstimatedDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedFunctions")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StageStartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalFunctions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Stage");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("PipelineExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Charter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ComplexityScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeploymentTarget")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetFramework")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.ProjectFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BuildOrder")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ContentSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Dependencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullPath")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GeneratedByAgent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GenerationPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverwritable")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Template")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ValidationResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentType");

                    b.HasIndex("FileName");

                    b.HasIndex("IsActive");

                    b.HasIndex("ModuleId");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RelativePath");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "RelativePath");

                    b.ToTable("ProjectFiles");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.StageExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("int");

                    b.Property<string>("InputData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("int");

                    b.Property<int?>("ItemsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<string>("OutputData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<string>("StageConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionOrder");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("StageName");

                    b.HasIndex("Status");

                    b.HasIndex("PipelineExecutionId", "ExecutionOrder");

                    b.ToTable("StageExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", "ParentExecution")
                        .WithMany("ChildExecutions")
                        .HasForeignKey("ParentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.StageExecution", "StageExecution")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("StageExecutionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentExecution");

                    b.Navigation("PipelineExecution");

                    b.Navigation("Project");

                    b.Navigation("StageExecution");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentMessage", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", "AgentExecution")
                        .WithMany("Messages")
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentMessage", "ParentMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AgentExecution");

                    b.Navigation("ParentMessage");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.CodeUnit", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.CrossReferenceEntity", "CrossReference")
                        .WithMany()
                        .HasForeignKey("CrossReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.DesignerOutput", "DesignerOutput")
                        .WithMany()
                        .HasForeignKey("DesignerOutputId");

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId");

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany()
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CrossReference");

                    b.Navigation("DesignerOutput");

                    b.Navigation("Module");

                    b.Navigation("PipelineExecution");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.DesignerOutput", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.CrossReferenceEntity", "CrossReference")
                        .WithMany()
                        .HasForeignKey("CrossReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CrossReference");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.FunctionSpecification", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", "AgentExecution")
                        .WithMany()
                        .HasForeignKey("AgentExecutionId");

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.CodeUnit", null)
                        .WithMany("FunctionSpecifications")
                        .HasForeignKey("CodeUnitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.CrossReferenceEntity", "CrossReference")
                        .WithMany()
                        .HasForeignKey("CrossReferenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.DesignerOutput", null)
                        .WithMany("FunctionSpecifications")
                        .HasForeignKey("DesignerOutputId");

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId");

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany()
                        .HasForeignKey("PipelineExecutionId");

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("AgentExecution");

                    b.Navigation("CrossReference");

                    b.Navigation("Module");

                    b.Navigation("PipelineExecution");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany("Modules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.OrchestrationResult", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.OrchestrationResult", "ParentOrchestration")
                        .WithMany("ChildOrchestrations")
                        .HasForeignKey("ParentOrchestrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany("OrchestrationResults")
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentOrchestration");

                    b.Navigation("PipelineExecution");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany("PipelineExecutions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.ProjectFile", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", "Module")
                        .WithMany("Files")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany()
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("PipelineExecution");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.StageExecution", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany("StageExecutions")
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PipelineExecution");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", b =>
                {
                    b.Navigation("ChildExecutions");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentMessage", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.CodeUnit", b =>
                {
                    b.Navigation("FunctionSpecifications");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.DesignerOutput", b =>
                {
                    b.Navigation("FunctionSpecifications");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.OrchestrationResult", b =>
                {
                    b.Navigation("ChildOrchestrations");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", b =>
                {
                    b.Navigation("AgentExecutions");

                    b.Navigation("OrchestrationResults");

                    b.Navigation("StageExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", b =>
                {
                    b.Navigation("AgentExecutions");

                    b.Navigation("Files");

                    b.Navigation("Modules");

                    b.Navigation("PipelineExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.StageExecution", b =>
                {
                    b.Navigation("AgentExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
