// <auto-generated />
using System;
using Ensemble.Maestro.Dotnet.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ensemble.Maestro.Dotnet.Migrations
{
    [DbContext(typeof(MaestroDbContext))]
    [Migration("20250827072248_FixDecimalPrecision")]
    partial class FixDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.7.25380.108")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AgentSpecialization")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("ContextData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ExecutionCost")
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("ExecutionLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionCalls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrchestrationPattern")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OutputResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerformanceMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PluginsUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<Guid?>("StageExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgentType");

                    b.HasIndex("ParentExecutionId");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StageExecutionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "AgentType", "Status");

                    b.ToTable("AgentExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ContentLength")
                        .HasColumnType("int");

                    b.Property<string>("ContextData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionCallData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionCallResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRetry")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationContext")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("int");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("int");

                    b.Property<bool>("TriggeredFunctionCall")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MessageType");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("Role");

                    b.HasIndex("SequenceNumber");

                    b.HasIndex("ThreadId");

                    b.HasIndex("AgentExecutionId", "SequenceNumber");

                    b.ToTable("AgentMessages");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ActualHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComplexityScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Dependencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleOrder")
                        .HasColumnType("int");

                    b.Property<string>("ModuleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalStack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ModuleOrder");

                    b.HasIndex("ModuleType");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.OrchestrationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgentCount")
                        .HasColumnType("int");

                    b.Property<string>("CancellationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("ContextData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DidTimeout")
                        .HasColumnType("bit");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionFlow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FunctionCallCount")
                        .HasColumnType("int");

                    b.Property<string>("InitialInput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InputTransformations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MessageCount")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrchestrationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrchestrationPattern")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OutputTransformations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentOrchestrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParticipatingAgents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<string>("RuntimeConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SuccessRate")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.Property<string>("Warnings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasCancelled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrchestrationPattern");

                    b.HasIndex("ParentOrchestrationId");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("OrchestrationResults");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActualDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("AgentPoolSize")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedFunctions")
                        .HasColumnType("int");

                    b.Property<string>("DeploymentTarget")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstimatedDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedFunctions")
                        .HasColumnType("int");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StageStartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalFunctions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Stage");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("PipelineExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Charter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ComplexityScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DeploymentTarget")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("EstimatedHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetFramework")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.ProjectFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BuildOrder")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("ContentSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Dependencies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FullPath")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("GeneratedByAgent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GenerationPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverwritable")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QualityScore")
                        .HasColumnType("int");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Template")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ValidationResults")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentType");

                    b.HasIndex("FileName");

                    b.HasIndex("IsActive");

                    b.HasIndex("ModuleId");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RelativePath");

                    b.HasIndex("Status");

                    b.HasIndex("ProjectId", "RelativePath");

                    b.ToTable("ProjectFiles");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.StageExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionLogs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("int");

                    b.Property<string>("InputData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("ItemsFailed")
                        .HasColumnType("int");

                    b.Property<int?>("ItemsProcessed")
                        .HasColumnType("int");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<string>("OutputData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PipelineExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("int");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.Property<string>("StageConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionOrder");

                    b.HasIndex("PipelineExecutionId");

                    b.HasIndex("StageName");

                    b.HasIndex("Status");

                    b.HasIndex("PipelineExecutionId", "ExecutionOrder");

                    b.ToTable("StageExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", "ParentExecution")
                        .WithMany("ChildExecutions")
                        .HasForeignKey("ParentExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.StageExecution", "StageExecution")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("StageExecutionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentExecution");

                    b.Navigation("PipelineExecution");

                    b.Navigation("Project");

                    b.Navigation("StageExecution");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentMessage", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", "AgentExecution")
                        .WithMany("Messages")
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentMessage", "ParentMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AgentExecution");

                    b.Navigation("ParentMessage");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany("Modules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.OrchestrationResult", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.OrchestrationResult", "ParentOrchestration")
                        .WithMany("ChildOrchestrations")
                        .HasForeignKey("ParentOrchestrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany("OrchestrationResults")
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentOrchestration");

                    b.Navigation("PipelineExecution");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany("PipelineExecutions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.ProjectFile", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", "Module")
                        .WithMany("Files")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany()
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("PipelineExecution");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.StageExecution", b =>
                {
                    b.HasOne("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", "PipelineExecution")
                        .WithMany("StageExecutions")
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PipelineExecution");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentExecution", b =>
                {
                    b.Navigation("ChildExecutions");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.AgentMessage", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Module", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.OrchestrationResult", b =>
                {
                    b.Navigation("ChildOrchestrations");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.PipelineExecution", b =>
                {
                    b.Navigation("AgentExecutions");

                    b.Navigation("OrchestrationResults");

                    b.Navigation("StageExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.Project", b =>
                {
                    b.Navigation("AgentExecutions");

                    b.Navigation("Files");

                    b.Navigation("Modules");

                    b.Navigation("PipelineExecutions");
                });

            modelBuilder.Entity("Ensemble.Maestro.Dotnet.Core.Data.Entities.StageExecution", b =>
                {
                    b.Navigation("AgentExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
